version: 0.0
os: linux

file_exists_behavior: RETAIN
files:
  - source: /
    destination: /var/www/game.g-learning.click
hooks:
  AfterInstall:
  - location: scripts/restart.sh
    timeout: 300
    runas: ubuntu