name: Lear github action
on: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Use default action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Anh Hieu pro vip + 1"
      - name: Log greet time
        run: echo "${{steps.greet.outputs.time}}"

