name: Container 
on: push

jobs: 
  node-docker:
    runs-on: ubuntu-latest
    services:
      app: 
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d {\"username\":\"hello33\",\"address\":\"Da nang\"}"
      - name: Get Users
        run: "curl -X GET http://localhost:3001/api/users"
  redis-docker:
    runs-on: ubuntu-latest
    container: 
      image: redis
      ports: 
        - "6379:6379"
    steps:
      - name: Test redis install
        run: 
          redis-cli ping
          cat /etc/os-release
