name: Container 
on: push

jobs: 
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
  redis-docker:
    runs-on: ubuntu-latest
    container: 
      image: redis:6.0.19-alpine
    steps:
      - name: Test redis install
        run: 
          redis-cli ping
          cat /etc/os-release
