name: Deploy FE
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test-and-build-source:
    runs-on: ubuntu-latest
    # need to add permission
    permissions:
      id-token: write
      contents: read
    steps:
      - name: setup source
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: install dependences 
        run: npm ci
      - name: unit test
        run: CI=true npm run test 
      - name: build
          # update env
        run: |
          sed -i 's/VUE_APP_BASE_URL=/VUE_APP_BASE_URL=${{secrets.VUE_APP_BASE_URL}}/g' .env.ci 
          cp .env.ci .env
          npm run build
      
        # Copy to S3
      - name: copy code to S3
        run: |
          mkdir deploy
          cp appspec.yml ./deploy
          cp laravel-echo-server.json ./deploy
          cp -r ./scripts ./deploy
          cp -r ./dist ./deploy
          zip -r project.zip ./deploy 
          aws s3 cp project.zip s3://codedeploy-vue3/project.zip
  deploy:
    needs:  test-and-build-source
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: notify for codedeploy
      run: |
        aws deploy create-deployment \
          --application-name laravel-deploy \
          --deployment-group-name laravel-codedeploy \
          --s3-location bucket=codedeploy-vue3,bundleType=zip,key=project.zip


